import { store } from './state.js';
import { importLivePackage, validateLivePackage } from './livePackageImporter.js';

const HPO_MATCH_FORMAT = 'HPO-MATCH';
const HPO_MATCH_VERSION = '1.0';
export function isHpoMatch(payload) { return !!payload && typeof payload === 'object' && payload.format === HPO_MATCH_FORMAT && payload.version === HPO_MATCH_VERSION && payload.direction === 'PERFORMANCE_OS_TO_ANDEBOL_STATS' && payload.metadata?.source === 'handball-performance-os' && !!payload.match?.id && Array.isArray(payload.players) && Array.isArray(payload.roster) && Array.isArray(payload.events); }
export function hpoToLivePackage(payload) { if (!isHpoMatch(payload)) throw new Error('Formato HPO-MATCH inválido ou direção não suportada.'); if (payload.events.length > 0) throw new Error('Este ficheiro já contém eventos. Para preparar um jogo novo, importa apenas o HPO-MATCH inicial do Performance OS.'); const match=payload.match; const homeId=String(match.homeTeamId||'home-team'); const awayId=String(match.awayTeamId||'away-team'); const homeName=String(match.homeTeamName||'Equipa Casa'); const awayName=String(match.awayTeamName||'Equipa Fora'); return { schemaVersion:'1.1.0',source:'handball-performance-os',match:{...match,homeTeamId:homeId,awayTeamId:awayId},teams:{home:{id:homeId,name:homeName},away:{id:awayId,name:awayName}},players:payload.players.map(p=>({id:String(p.id),teamId:p.teamId!=null?String(p.teamId):null,name:p.name||'',displayName:p.name||'',shirtNumber:p.shirtNumber??'',position:p.position||'',hpi:p.hpi??null})),roster:payload.roster,events:[] }; }
function buildImportedState(payload, imported) { const nextState=store.getInitialState(); nextState.matchId=imported.matchId; nextState.teamAName=imported.teamAName; nextState.teamBName=imported.teamBName; nextState.teamAId=imported.teamAId; nextState.teamBId=imported.teamBId; nextState.halfDuration=Number(payload.match.durationMinutes||30); nextState.currentGamePart=1; nextState.totalSeconds=0; nextState.isRunning=false; nextState.gameEvents=[]; nextState.gameSituationLog=[{startTime:0,endTime:null,situationA:'equality',situationB:'equality'}]; nextState.lastKnownSituations={A:'equality',B:'equality'}; const makePlayer=p=>({...p,id:String(p.id),teamId:String(p.teamId),sourceId:String(p.sourceId||p.id),Numero:p.Numero??'',Nome:p.Nome||'',Posicao:p.Posicao||'',onCourt:Boolean(p.onCourt),timeOnCourt:0,history:[],positiveActions:[],negativeActions:[],sanctions:{yellow:0,twoMin:0,red:0}}); nextState.gameData.A.players=imported.playersA.map(makePlayer); nextState.gameData.B.players=imported.playersB.map(makePlayer); nextState.gameData.A.officials=[]; nextState.gameData.B.officials=[]; nextState.gameData.A.fileLoaded=true; nextState.gameData.B.fileLoaded=true; nextState.gameData.A.stats={...nextState.gameData.A.stats,goals:0,misses:0,savedShots:0,turnovers:0,gkSaves:0,gkGoalsAgainst:0,technical_faults:0}; nextState.gameData.B.stats={...nextState.gameData.B.stats,goals:0,misses:0,savedShots:0,turnovers:0,gkSaves:0,gkGoalsAgainst:0,technical_faults:0}; return nextState; }
async function importMatchFile(file){const payload=JSON.parse(await file.text());let sourcePayload=payload;let validation;if(isHpoMatch(payload)){sourcePayload=hpoToLivePackage(payload);validation=validateLivePackage(sourcePayload);}else{validation=validateLivePackage(payload);if(payload.source!=='handball-performance-os')throw new Error('Ficheiro recusado: o jogo tem de ser exportado pelo Handball Performance OS.');if((payload.events||[]).length>0)throw new Error('Este ficheiro já contém eventos. Para preparar um jogo novo, importa apenas o HPO-MATCH inicial do Performance OS.');}if(!validation.valid)throw new Error(validation.errors.join('\n'));const imported=importLivePackage(sourcePayload);const nextState=buildImportedState(payload,imported);const confirmed=confirm(`JOGO DO PERFORMANCE OS\n\n${imported.teamAName} vs ${imported.teamBName}\nJogadores casa: ${nextState.gameData.A.players.length}\nJogadores fora: ${nextState.gameData.B.players.length}\nDuração: ${nextState.halfDuration} min\nEstado inicial: 0-0\n\nConfirmar importação?`);if(!confirmed)return false;sessionStorage.setItem('handballGameSession',JSON.stringify(nextState));window.location.reload();return true;}
function createInput(){let input=document.getElementById('importPerformanceOSInput');if(input)return input;input=document.createElement('input');input.id='importPerformanceOSInput';input.type='file';input.accept='.json,application/json';input.hidden=true;document.body.appendChild(input);input.addEventListener('change',async()=>{const file=input.files?.[0];input.value='';if(!file)return;try{await importMatchFile(file);}catch(error){console.error('[Performance OS Import] Erro:',error);alert(`Não foi possível importar o jogo.\n\n${error instanceof Error?error.message:'Ficheiro inválido.'}`);}});return input;}
function addButton(parent,id,text){let button=document.getElementById(id);if(button)return button;button=document.createElement('button');button.id=id;button.type='button';button.className='w-full bg-indigo-700 hover:bg-indigo-600 text-white font-bold py-3 px-4 rounded-lg transition flex items-center justify-center gap-2';button.textContent=text;parent.appendChild(button);return button;}
function installWelcomeLoader(){const modal=document.getElementById('welcomeModal');if(!modal)return;const input=createInput();const legacyFile=document.getElementById('welcome-file-input-A');const legacyName=document.getElementById('file-name-A');const legacyOpponent=document.getElementById('welcome-team-b-name');const legacyStart=document.getElementById('startGameBtn');const durationBlock=document.querySelector('#welcomeModal input[name="gameDuration"]')?.closest('.bg-gray-700');legacyFile?.closest('div')?.parentElement?.classList.add('hidden');legacyName?.classList.add('hidden');legacyOpponent?.classList.add('hidden');legacyStart?.classList.add('hidden');durationBlock?.classList.add('hidden');const container=modal.querySelector('.space-y-4');if(!container)return;const title=modal.querySelector('h2');if(title)title.textContent='Importar Jogo';if(!document.getElementById('performanceOSImportHint')){const subtitle=document.createElement('p');subtitle.id='performanceOSImportHint';subtitle.className='text-sm text-gray-300 mb-4';subtitle.textContent='O jogo é criado no Performance OS. O Andebol-Stats recebe as duas equipas e os dois plantéis através do HPO-MATCH.';container.prepend(subtitle);}const button=addButton(container,'importPerformanceOSBtn','📥 Importar jogo do Performance OS');button.onclick=()=>input.click();}
function installMainLoader(){const exportButton=document.getElementById('exportCanonicalMatchBtn');const excelButton=document.getElementById('exportExcelBtn');const anchor=exportButton||excelButton;if(!anchor?.parentElement)return;const input=createInput();const button=addButton(anchor.parentElement,'importCanonicalMatchBtn','📥 Importar Performance OS');button.className='flex-1 bg-indigo-700 hover:bg-indigo-600 text-white py-2 rounded-lg font-bold';button.onclick=()=>input.click();}
function installImportUI(){installWelcomeLoader();installMainLoader();}
if(typeof document!=='undefined'){if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',installImportUI,{once:true});else installImportUI();setTimeout(installImportUI,500);setTimeout(installImportUI,1500);}
