import { store } from '../state.js';
import { calculateMatchAnalytics, calculateShotAnalytics } from '../domain/analytics.js';
import { calculateAllPlayerAnalytics } from '../domain/playerAnalytics.js';

function pct(v){return v==null||!Number.isFinite(Number(v))?'—':`${Number(v).toFixed(1)}%`;}
function seconds(v){const n=Number(v);return Number.isFinite(n)?`${Math.floor(n/60).toString().padStart(2,'0')}:${Math.floor(n%60).toString().padStart(2,'0')}`:'—';}
function value(v){return Number.isFinite(Number(v))?Number(v):0;}
function esc(v){return String(v??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));}

function teamCard(name,t){
 const rows=[['Posses',t.possessions],['Golos',t.goals],['Remates',t.shots],['Defesas GR',t.saves],['Golos sofridos',t.goals_conceded],['Remates falhados',t.missed],['Postes',t.post],['Remates bloqueados',t.blocked],['Perdas de bola',t.turnovers],['Roubos de bola',t.steals],['Interceções',t.interceptions],['Recuperações',t.recoveries],['7 metros ganhos',t.seven_meter_won]];
 return `<div class="bg-gray-900 rounded-xl p-4 border border-gray-700"><h4 class="text-xl font-bold text-white mb-4">${esc(name)}</h4><div class="grid md:grid-cols-2 gap-3 mb-4"><div class="bg-gray-800 rounded-lg p-3 text-center"><div class="text-xs text-gray-400">Eficiência ataque</div><div class="text-2xl font-bold text-white">${pct(t.attack_efficiency)}</div></div><div class="bg-gray-800 rounded-lg p-3 text-center"><div class="text-xs text-gray-400">Eficiência remate</div><div class="text-2xl font-bold text-white">${pct(t.shot_efficiency)}</div></div><div class="bg-gray-800 rounded-lg p-3 text-center"><div class="text-xs text-gray-400">Eficácia GR</div><div class="text-2xl font-bold text-white">${pct(t.goalkeeper_save_efficiency)}</div></div><div class="bg-gray-800 rounded-lg p-3 text-center"><div class="text-xs text-gray-400">Duração média ataque</div><div class="text-2xl font-bold text-white">${seconds(t.average_attack_duration_seconds)}</div></div><div class="bg-gray-800 rounded-lg p-3 text-center"><div class="text-xs text-gray-400">Transições</div><div class="text-2xl font-bold text-white">${value(t.transition_attacks)}</div></div></div><div class="space-y-1">${rows.map(([l,v])=>`<div class="flex justify-between border-b border-gray-800 py-1.5 text-sm"><span class="text-gray-400">${l}</span><span class="font-bold text-white">${value(v)}</span></div>`).join('')}</div></div>`;
}

function playerTable(name,players){if(!players.length)return '';const rows=players.map(p=>`<tr class="border-b border-gray-800"><td class="px-2 py-2 text-white font-semibold whitespace-nowrap">${esc(p.number||'—')} · ${esc(p.name)}</td><td class="px-2 py-2 text-center">${p.minutes.toFixed(1)}</td><td class="px-2 py-2 text-center">${p.shots}</td><td class="px-2 py-2 text-center font-bold">${p.goals}</td><td class="px-2 py-2 text-center">${pct(p.shotEfficiency)}</td><td class="px-2 py-2 text-center">${p.goalkeeperSaves}</td><td class="px-2 py-2 text-center">${p.missed}</td><td class="px-2 py-2 text-center">${p.post}</td><td class="px-2 py-2 text-center">${p.blocked}</td><td class="px-2 py-2 text-center">${p.turnovers}</td><td class="px-2 py-2 text-center">${p.assists}</td><td class="px-2 py-2 text-center">${p.steals}</td><td class="px-2 py-2 text-center">${p.interceptions}</td><td class="px-2 py-2 text-center">${p.positive}</td><td class="px-2 py-2 text-center">${p.negative}</td><td class="px-2 py-2 text-center">${p.yellow}</td><td class="px-2 py-2 text-center">${p.twoMin}</td><td class="px-2 py-2 text-center">${p.red}</td></tr>`).join('');return `<div class="bg-gray-900 rounded-xl p-4 border border-gray-700 mt-4"><h4 class="text-lg font-bold text-white mb-3">${esc(name)} · Jogadores</h4><div class="overflow-x-auto"><table class="w-full text-xs text-gray-300"><thead><tr class="border-b border-gray-700 text-gray-400"><th class="px-2 py-2 text-left">Jogador</th><th>Min</th><th>R</th><th>G</th><th>Efic. R</th><th>Def GR</th><th>Falh.</th><th>Postes</th><th>Bloq.</th><th>Perdas</th><th>Ass.</th><th>Roubos</th><th>Interc.</th><th>Pos.</th><th>Neg.</th><th>🟨</th><th>2'</th><th>🟥</th></tr></thead><tbody>${rows}</tbody></table></div><div class="text-xs text-gray-500 mt-2">Min = minutos em campo · R = remates · G = golos · Efic. R = eficácia de remate</div></div>`;}

function shotCell(bucket,max){const n=value(bucket.shots);const intensity=max?Math.max(.08,n/max):.08;return `<div class="rounded-lg border border-gray-700 p-2 text-center" style="background:rgba(37,99,235,${intensity.toFixed(2)})"><div class="text-xl font-black text-white">${n}</div><div class="text-[10px] text-gray-300">${value(bucket.goals)} G · ${pct(bucket.efficiency)}</div></div>`;}

function zoneDistanceStats(name,data){
 const zones=['1','2','3','4','5','6','7','8','9'];const distances=['curta','curta/média','média','longa','7m'];
 const all=Object.values(data.by_zone_distance);const max=Math.max(0,...all.map(b=>value(b.shots)));
 return `<section class="bg-gray-900 rounded-xl p-4 border border-gray-700 mt-4"><div class="flex items-center justify-between gap-3 mb-3"><div><h4 class="text-lg font-bold text-white">${esc(name)} · Zona × Distância</h4><p class="text-xs text-gray-400">Remates · Golos · Eficácia de remate</p></div></div><div class="overflow-x-auto"><table class="w-full min-w-[760px] text-xs text-gray-300"><thead><tr class="border-b border-gray-700 text-gray-400"><th class="text-left p-2">Zona</th>${distances.map(d=>`<th class="p-2">${d}</th>`).join('')}<th class="p-2">Total</th></tr></thead><tbody>${zones.map(z=>{const bs=distances.map(d=>data.by_zone_distance[`${z}::${d}`]||{shots:0,goals:0,efficiency:null});const total=bs.reduce((a,b)=>a+value(b.shots),0);return `<tr class="border-b border-gray-800"><td class="p-2 font-bold text-white">${z}</td>${bs.map(b=>`<td class="p-1">${shotCell(b,max)}</td>`).join('')}<td class="p-2 text-center font-bold text-white">${total}</td></tr>`;}).join('')}</tbody></table></div></section>`;
}

function zoneHeatmap(name,data){const zones=['1','2','3','4','5','6','7','8','9'];const max=Math.max(0,...zones.map(z=>value(data.by_zone[z]?.shots)));return `<section class="bg-gray-900 rounded-xl p-4 border border-gray-700"><h4 class="text-lg font-bold text-white mb-1">${esc(name)} · Heatmap por zona</h4><p class="text-xs text-gray-400 mb-3">Intensidade = número de remates. Cada célula mostra remates, golos e eficácia.</p><div class="grid grid-cols-5 gap-2 max-w-3xl mx-auto"><div></div>${zones.slice(0,5).map(z=>`<div>${shotCell(data.by_zone[z],max)}<div class="text-center text-[10px] text-gray-500 mt-1">Z${z}</div></div>`).join('')}<div></div>${zones.slice(5,8).map(z=>`<div>${shotCell(data.by_zone[z],max)}<div class="text-center text-[10px] text-gray-500 mt-1">Z${z}</div></div>`).join('')}<div></div><div>${shotCell(data.by_zone['9'],max)}<div class="text-center text-[10px] text-gray-500 mt-1">Z9</div></div></div></section>`;}

function goalHeatmap(name,data){const cells=['1','2','3','4','5','6','7','8','9'];const max=Math.max(0,...cells.map(z=>value(data.goal?.[z]?.shots)));return `<section class="bg-gray-900 rounded-xl p-4 border border-gray-700"><h4 class="text-lg font-bold text-white mb-1">${esc(name)} · Heatmap por baliza</h4><p class="text-xs text-gray-400 mb-3">Localização 1–9 da baliza. Intensidade = número de remates.</p><div class="grid grid-cols-3 gap-2 max-w-xl mx-auto border-2 border-gray-600 rounded-lg p-2">${cells.map(z=>shotCell(data.goal?.[z]||{shots:0,goals:0,efficiency:null},max)).join('')}</div></section>`;}

function distanceCards(name,data){return `<section class="bg-gray-900 rounded-xl p-4 border border-gray-700"><h4 class="text-lg font-bold text-white mb-3">${esc(name)} · Estatística por distância</h4><div class="grid grid-cols-2 md:grid-cols-5 gap-2">${['curta','curta/média','média','longa','7m'].map(d=>{const b=data.by_distance[d];return `<div class="bg-gray-800 rounded-lg p-3 text-center"><div class="text-xs text-gray-400">${d}</div><div class="text-2xl font-black text-white">${value(b.shots)}</div><div class="text-xs text-gray-300">${value(b.goals)} golos</div><div class="text-xs text-gray-400">${pct(b.efficiency)}</div></div>`}).join('')}</div></section>`;}

function shotAnalytics(name,data){return `<div class="mt-6"><div class="mb-3"><h3 class="text-2xl font-black text-white">Análise dos remates · ${esc(name)}</h3><p class="text-sm text-gray-400">Protocolo próprio: zonas 1–9 e distâncias definidas no registo do remate.</p></div>${distanceCards(name,data)}${zoneDistanceStats(name,data)}<div class="grid lg:grid-cols-2 gap-4 mt-4">${zoneHeatmap(name,data)}${goalHeatmap(name,data)}</div></div>`;}

export function renderAnalyticsPanel(){const container=document.getElementById('stats-comparison-container');if(!container)return;const state=store.state;const analytics=calculateMatchAnalytics(state);const shots=analytics.shots||calculateShotAnalytics(state);const players=calculateAllPlayerAnalytics(state);const nameA=state.teamAName||'Equipa A',nameB=state.teamBName||'Equipa B';container.dataset.analyticsPanel='active';container.innerHTML=`<div class="mb-4 text-center"><div class="text-sm text-gray-400">Análise em tempo real</div><div class="text-xs text-gray-500">Eventos registados: ${analytics.total_events} · Cronómetro: ${seconds(analytics.updated_at_seconds)}</div></div><div class="grid md:grid-cols-2 gap-4">${teamCard(nameA,analytics.A)}${teamCard(nameB,analytics.B)}</div>${playerTable(nameA,players.A)}${playerTable(nameB,players.B)}${shotAnalytics(nameA,shots.A)}${shotAnalytics(nameB,shots.B)}`;}

if(typeof window!=='undefined'&&!window.__handballAnalyticsUIInstalled){window.__handballAnalyticsUIInstalled=true;let observer=null,rendering=false,scheduled=false;const renderSafely=()=>{if(scheduled)return;scheduled=true;window.setTimeout(()=>{scheduled=false;if(rendering)return;const c=document.getElementById('stats-comparison-container');if(!c)return;rendering=true;if(observer)observer.disconnect();try{renderAnalyticsPanel();}finally{rendering=false;if(observer)observer.observe(c,{childList:true,subtree:true});}},0);};window.addEventListener('handball:state-updated',renderSafely);document.addEventListener('click',event=>{const button=event.target.closest?.('.tab-link');if(button?.dataset?.tab==='stats')renderSafely();},true);const installObserver=()=>{const c=document.getElementById('stats-comparison-container');if(!c){window.setTimeout(installObserver,100);return;}observer=new MutationObserver(()=>{if(!rendering)renderSafely();});observer.observe(c,{childList:true,subtree:true});renderSafely();};installObserver();}
