import {store} from '../state.js';
import {calculateMatchAnalytics,calculateShotAnalytics} from '../domain/analytics.js';
const pct=v=>v==null||!Number.isFinite(Number(v))?'—':`${Number(v).toFixed(1)}%`;
const val=v=>Number.isFinite(Number(v))?Number(v):0;
const sec=v=>Number.isFinite(Number(v))?`${Math.floor(v/60).toString().padStart(2,'0')}:${Math.floor(v%60).toString().padStart(2,'0')}`:'—';
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function shotCell(b,max){const n=val(b?.shots),a=max?Math.max(.08,n/max):.08;return `<div class="rounded-lg border border-gray-700 p-2 text-center" style="background:rgba(37,99,235,${a.toFixed(2)})"><div class="text-xl font-black text-white">${n}</div><div class="text-[10px] text-gray-300">${val(b?.goals)} G · ${pct(b?.efficiency)}</div></div>`;}
function zoneHeat(name,d){const zs=['1','2','3','4','5','6','7','8','9'],max=Math.max(0,...zs.map(z=>val(d.by_zone?.[z]?.shots))),cell=z=>`<div>${shotCell(d.by_zone?.[z],max)}<div class="text-center text-xs text-gray-500">Z${z}</div></div>`;return `<section class="bg-gray-900 rounded-xl p-4 border border-gray-700"><h4 class="text-lg font-bold text-white mb-1">${esc(name)} · Heatmap por zona</h4><p class="text-xs text-gray-400 mb-3">Intensidade = número de remates.</p><div class="grid grid-cols-5 gap-2">${['1','2','3','4','5'].map(cell).join('')}<div></div>${['6','7','8'].map(cell).join('')}<div></div><div></div><div></div>${cell('9')}<div></div><div></div></div></section>`;}
function goalHeat(name,d){const zs=['1','2','3','4','5','6','7','8','9'],max=Math.max(0,...zs.map(z=>val(d.by_goal?.[z]?.shots)));return `<section class="bg-gray-900 rounded-xl p-4 border border-gray-700"><h4 class="text-lg font-bold text-white mb-1">${esc(name)} · Heatmap por baliza</h4><p class="text-xs text-gray-400 mb-3">Localização 1–9 da baliza.</p><div class="grid grid-cols-3 gap-2 max-w-xl mx-auto">${zs.map(z=>shotCell(d.by_goal?.[z],max)).join('')}</div></section>`;}
function distances(name,d){return `<section class="bg-gray-900 rounded-xl p-4 border border-gray-700"><h4 class="text-lg font-bold text-white mb-3">${esc(name)} · Distâncias</h4><div class="grid grid-cols-1 md:grid-cols-3 gap-2">${['curta','média','longa'].map(x=>{const b=d.by_distance?.[x]||{};return `<div class="bg-gray-800 rounded-lg p-3 text-center"><div class="text-xs text-gray-400">${x}</div><div class="text-2xl font-black text-white">${val(b.shots)}</div><div class="text-xs text-gray-300">${val(b.goals)} golos · ${pct(b.efficiency)}</div></div>`}).join('')}</div></section>`;}
function zoneDistance(name,d){const zs=['1','2','3','4','5','6','7','8','9'],ds=['curta','média','longa'];return `<section class="bg-gray-900 rounded-xl p-4 border border-gray-700 mt-4"><h4 class="text-lg font-bold text-white">${esc(name)} · Zona × Distância</h4><div class="overflow-x-auto"><table class="w-full text-xs text-gray-300"><thead><tr><th class="p-2 text-left">Zona</th>${ds.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${zs.map(z=>`<tr class="border-b border-gray-800"><td class="p-2 font-bold text-white">${z}</td>${ds.map(x=>`<td class="p-1">${shotCell(d.by_zone_distance?.[`${z}::${x}`]||{},1)}</td>`).join('')}</tr>`).join('')}</tbody></table></div></section>`;}
function teamCard(name,t){return `<div class="bg-gray-900 rounded-xl p-4 border border-gray-700"><h4 class="text-xl font-bold text-white mb-3">${esc(name)}</h4><div class="grid grid-cols-2 gap-2">${[['Posses',t.possessions],['Golos',t.goals],['Remates',t.shots],['Eficácia',pct(t.shot_efficiency)],['Defesas GR',t.saves],['Perdas',t.turnovers]].map(([l,v])=>`<div class="bg-gray-800 rounded p-3"><div class="text-xs text-gray-400">${l}</div><div class="text-xl font-bold">${v}</div></div>`).join('')}</div></div>`;}
function renderHeatmapsPanel(){const c=document.getElementById('tab-heatmap');if(!c)return;const a=calculateMatchAnalytics(store.state),sh=a.shots||calculateShotAnalytics(store.state),A=store.state.teamAName||'Equipa A',B=store.state.teamBName||'Equipa B';c.innerHTML=`<div class="bg-gray-800 p-4 md:p-6 rounded-2xl shadow-lg"><h3 class="text-2xl font-bold text-center mb-6">Heatmaps</h3><div class="grid lg:grid-cols-2 gap-4">${zoneHeat(A,sh.A)}${zoneHeat(B,sh.B)}${goalHeat(A,sh.A)}${goalHeat(B,sh.B)}</div></div>`;}
export function renderAnalyticsPanel(){const c=document.getElementById('stats-comparison-container');if(!c)return;const a=calculateMatchAnalytics(store.state),sh=a.shots||calculateShotAnalytics(store.state),A=store.state.teamAName||'Equipa A',B=store.state.teamBName||'Equipa B';c.innerHTML=`<div class="mb-4 text-center text-xs text-gray-400">Eventos: ${a.total_events} · Cronómetro: ${sec(a.updated_at_seconds)}</div><div class="grid md:grid-cols-2 gap-4">${teamCard(A,a.A)}${teamCard(B,a.B)}</div>${[A,B].map((n,i)=>{const d=sh[i?'B':'A'];return `<div class="mt-6"><h3 class="text-xl font-bold">${esc(n)} · Análise de remates</h3>${distances(n,d)}${zoneDistance(n,d)}</div>`}).join('')}`;}
if(typeof window!=='undefined'&&!window.__handballAnalyticsUIInstalled){window.__handballAnalyticsUIInstalled=true;const render=()=>{renderAnalyticsPanel();renderHeatmapsPanel();};window.addEventListener('handball:state-updated',render);document.addEventListener('click',e=>{const tab=e.target.closest?.('.tab-link')?.dataset?.tab;if(tab==='stats'||tab==='heatmap')render();},true);setTimeout(render,0);}
