import {store} from '../state.js';
import {calculateMatchAnalytics,calculateShotAnalytics} from '../domain/analytics.js';
import {calculateAllPlayerAnalytics} from '../domain/playerAnalytics.js';
const pct=v=>v==null||!Number.isFinite(Number(v))?'—':`${Number(v).toFixed(1)}%`;
const sec=v=>{const n=Number(v);return Number.isFinite(n)?`${Math.floor(n/60).toString().padStart(2,'0')}:${Math.floor(n%60).toString().padStart(2,'0')}`:'—';};
const val=v=>Number.isFinite(Number(v))?Number(v):0;
const esc=v=>String(v??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));
function teamCard(name,t){const rows=[['Posses',t.possessions],['Golos',t.goals],['Remates',t.shots],['Defesas GR',t.saves],['Golos sofridos',t.goals_conceded],['Remates falhados',t.missed],['Postes',t.post],['Remates bloqueados',t.blocked],['Perdas de bola',t.turnovers],['Roubos de bola',t.steals],['Interceções',t.interceptions],['Recuperações',t.recoveries],['7 metros ganhos',t.seven_meter_won]];return `<div class="bg-gray-900 rounded-xl p-4 border border-gray-700"><h4 class="text-xl font-bold text-white mb-4">${esc(name)}</h4><div class="grid md:grid-cols-2 gap-3 mb-4"><div class="bg-gray-800 rounded-lg p-3 text-center"><div class="text-xs text-gray-400">Eficiência ataque</div><div class="text-2xl font-bold text-white">${pct(t.attack_efficiency)}</div></div><div class="bg-gray-800 rounded-lg p-3 text-center"><div class="text-xs text-gray-400">Eficiência remate</div><div class="text-2xl font-bold text-white">${pct(t.shot_efficiency)}</div></div><div class="bg-gray-800 rounded-lg p-3 text-center"><div class="text-xs text-gray-400">Eficácia GR</div><div class="text-2xl font-bold text-white">${pct(t.goalkeeper_save_efficiency)}</div></div><div class="bg-gray-800 rounded-lg p-3 text-center"><div class="text-xs text-gray-400">Duração média ataque</div><div class="text-2xl font-bold text-white">${sec(t.average_attack_duration_seconds)}</div></div></div><div>${rows.map(([l,v])=>`<div class="flex justify-between border-b border-gray-800 py-1.5 text-sm"><span class="text-gray-400">${l}</span><b class="text-white">${val(v)}</b></div>`).join('')}</div></div>`;}
function playerTable(name,ps){if(!ps.length)return '';const rows=ps.map(p=>`<tr class="border-b border-gray-800"><td class="p-2 text-white font-semibold">${esc(p.number||'—')} · ${esc(p.name)}</td><td class="p-2 text-center">${p.minutes.toFixed(1)}</td><td class="p-2 text-center">${p.shots}</td><td class="p-2 text-center font-bold">${p.goals}</td><td class="p-2 text-center">${pct(p.shotEfficiency)}</td><td class="p-2 text-center">${p.goalkeeperSaves}</td><td class="p-2 text-center">${p.missed}</td><td class="p-2 text-center">${p.post}</td><td class="p-2 text-center">${p.blocked}</td><td class="p-2 text-center">${p.turnovers}</td><td class="p-2 text-center">${p.assists}</td></tr>`).join('');return `<div class="bg-gray-900 rounded-xl p-4 border border-gray-700 mt-4"><h4 class="text-lg font-bold text-white mb-3">${esc(name)} · Jogadores</h4><div class="overflow-x-auto"><table class="w-full text-xs text-gray-300"><thead><tr class="border-b border-gray-700 text-gray-400"><th class="p-2 text-left">Jogador</th><th>Min</th><th>R</th><th>G</th><th>Efic. R</th><th>Def GR</th><th>Falh.</th><th>Postes</th><th>Bloq.</th><th>Perdas</th><th>Ass.</th></tr></thead><tbody>${rows}</tbody></table></div></div>`;}
function shotCell(b,max){const n=val(b?.shots),a=max?Math.max(.08,n/max):.08;return `<div class="rounded-lg border border-gray-700 p-2 text-center" style="background:rgba(37,99,235,${a.toFixed(2)})"><div class="text-xl font-black text-white">${n}</div><div class="text-[10px] text-gray-300">${val(b?.goals)} G · ${pct(b?.efficiency)}</div></div>`;}
function distanceTable(name,d){const zs=['1','2','3','4','5','6','7','8','9'],ds=['curta','média','longa'],all=Object.values(d.by_zone_distance),max=Math.max(0,...all.map(b=>val(b.shots)));return `<section class="bg-gray-900 rounded-xl p-4 border border-gray-700 mt-4"><h4 class="text-lg font-bold text-white">${esc(name)} · Zona × Distância</h4><p class="text-xs text-gray-400 mb-3">Remates · Golos · Eficácia</p><div class="overflow-x-auto"><table class="w-full min-w-[520px] text-xs text-gray-300"><thead><tr class="border-b border-gray-700"><th class="p-2 text-left">Zona</th>${ds.map(x=>`<th class="p-2">${x}</th>`).join('')}<th>Total</th></tr></thead><tbody>${zs.map(z=>{const bs=ds.map(x=>d.by_zone_distance[`${z}::${x}`]||{});return `<tr class="border-b border-gray-800"><td class="p-2 font-bold text-white">${z}</td>${bs.map(b=>`<td class="p-1">${shotCell(b,max)}</td>`).join('')}<td class="p-2 text-center font-bold text-white">${bs.reduce((a,b)=>a+val(b.shots),0)}</td></tr>`}).join('')}</tbody></table></div></section>`;}
function zoneHeat(name,d){const zs=['1','2','3','4','5','6','7','8','9'],max=Math.max(0,...zs.map(z=>val(d.by_zone[z]?.shots)));return `<section class="bg-gray-900 rounded-xl p-4 border border-gray-700"><h4 class="text-lg font-bold text-white mb-1">${esc(name)} · Heatmap por zona</h4><p class="text-xs text-gray-400 mb-3">Intensidade = número de remates.</p><div class="grid grid-cols-5 gap-2">${zs.slice(0,5).map(z=>`<div>${shotCell(d.by_zone[z],max)}<div class="text-center text-xs text-gray-500">Z${z}</div></div>`).join('')}<div></div>${zs.slice(5,8).map(z=>`<div>${shotCell(d.by_zone[z],max)}<div class="text-center text-xs text-gray-500">Z${z}</div></div>`).join('')}<div></div><div>${shotCell(d.by_zone['9'],max)}<div class="text-center text-xs text-gray-500">Z9</div></div></div></section>`;}
function goalHeat(name,d){const zs=['1','2','3','4','5','6','7','8','9'],max=Math.max(0,...zs.map(z=>val(d.by_goal?.[z]?.shots)));return `<section class="bg-gray-900 rounded-xl p-4 border border-gray-700"><h4 class="text-lg font-bold text-white mb-1">${esc(name)} · Heatmap por baliza</h4><p class="text-xs text-gray-400 mb-3">Localização 1–9 da baliza. Intensidade = número de remates.</p><div class="grid grid-cols-3 gap-2 max-w-xl mx-auto border-2 border-gray-600 rounded-lg p-2">${zs.map(z=>shotCell(d.by_goal?.[z],max)).join('')}</div></section>`;}
function distances(name,d){return `<section class="bg-gray-900 rounded-xl p-4 border border-gray-700"><h4 class="text-lg font-bold text-white mb-3">${esc(name)} · Estatística por distância</h4><div class="grid grid-cols-1 md:grid-cols-3 gap-2">${['curta','média','longa'].map(x=>{const b=d.by_distance[x]||{};return `<div class="bg-gray-800 rounded-lg p-3 text-center"><div class="text-xs text-gray-400">${x}</div><div class="text-2xl font-black text-white">${val(b.shots)}</div><div class="text-xs text-gray-300">${val(b.goals)} golos</div><div class="text-xs text-gray-400">${pct(b.efficiency)}</div></div>`}).join('')}</div></section>`;}
function shotAnalytics(name,d){return `<div class="mt-6"><h3 class="text-2xl font-black text-white mb-1">Análise dos remates · ${esc(name)}</h3><p class="text-sm text-gray-400">Protocolo próprio: zonas 1–9 e distâncias curta, média e longa.</p>${distances(name,d)}${distanceTable(name,d)}<div class="grid lg:grid-cols-2 gap-4 mt-4">${zoneHeat(name,d)}${goalHeat(name,d)}</div></div>`;}
export function renderAnalyticsPanel(){const c=document.getElementById('stats-comparison-container');if(!c)return;const s=store.state,a=calculateMatchAnalytics(s),sh=a.shots||calculateShotAnalytics(s),ps=calculateAllPlayerAnalytics(s),A=s.teamAName||'Equipa A',B=s.teamBName||'Equipa B';c.dataset.analyticsPanel='active';c.innerHTML=`<div class="mb-4 text-center"><div class="text-sm text-gray-400">Análise em tempo real</div><div class="text-xs text-gray-500">Eventos registados: ${a.total_events} · Cronómetro: ${sec(a.updated_at_seconds)}</div></div><div class="grid md:grid-cols-2 gap-4">${teamCard(A,a.A)}${teamCard(B,a.B)}</div>${playerTable(A,ps.A)}${playerTable(B,ps.B)}${shotAnalytics(A,sh.A)}${shotAnalytics(B,sh.B)}`;}
if(typeof window!=='undefined'&&!window.__handballAnalyticsUIInstalled){window.__handballAnalyticsUIInstalled=true;let observer=null,busy=false,scheduled=false;const render=()=>{if(scheduled)return;scheduled=true;setTimeout(()=>{scheduled=false;if(busy)return;const c=document.getElementById('stats-comparison-container');if(!c)return;busy=true;observer?.disconnect();try{renderAnalyticsPanel();}finally{busy=false;observer?.observe(c,{childList:true,subtree:true});}},0)};window.addEventListener('handball:state-updated',render);document.addEventListener('click',e=>{if(e.target.closest?.('.tab-link')?.dataset?.tab==='stats')render()},true);const install=()=>{const c=document.getElementById('stats-comparison-container');if(!c)return setTimeout(install,100);observer=new MutationObserver(()=>{if(!busy)render()});observer.observe(c,{childList:true,subtree:true});render()};install();}
