import { store } from '../state.js';
let active={side:null,shooterId:null,assist:null,imbalance:null};
const id=p=>p?.id??p?.Numero??p?.number;
const name=p=>`#${p?.Numero??p?.number??''} ${p?.Nome??p?.name??''}`.trim();
const teamPlayers=()=>store.state.gameData?.[active.side]?.players||[];
const onCourt=()=>teamPlayers().filter(p=>p.onCourt&&String(id(p))!==String(active.shooterId));
const find=x=>onCourt().find(p=>String(id(p))===String(x));
function render(){const m=document.getElementById('shotModal');if(!m||m.classList.contains('hidden')||!active.side)return;let p=m.querySelector('#shot-attribution-panel');if(!p){p=document.createElement('section');p.id='shot-attribution-panel';p.className='mt-4 rounded-xl bg-gray-900 p-3 border border-gray-700 text-left';p.innerHTML='<h4 class="font-bold mb-3">Construção da jogada</h4><b>Assistência</b><div id="shot-assist-options" class="grid grid-cols-2 gap-2 mb-3"></div><b>Desequilíbrio</b><div id="shot-imbalance-options" class="grid grid-cols-2 gap-2"></div>';const target=m.querySelector('#shotOutcomeContainer')||m.querySelector('.bg-gray-800');(target||m).appendChild(p);}for(const k of ['assist','imbalance']){const box=m.querySelector(`#shot-${k}-options`);if(!box)continue;box.innerHTML='';[['Nenhum',null],...onCourt().map(x=>[name(x),String(id(x))])].forEach(([txt,val])=>{const b=document.createElement('button');b.type='button';b.textContent=txt;b.className='shot-ui-btn';if(String(active[k])===String(val))b.classList.add('shot-zone-selected');b.onclick=()=>{active[k]=val;if(active.assist&&active.assist===active.imbalance)active[k]=null;window.__pendingShotAttribution={assist_player_id:active.assist,assist_player_name:find(active.assist)?name(find(active.assist)):null,imbalance_player_id:active.imbalance,imbalance_player_name:find(active.imbalance)?name(find(active.imbalance)):null,construction_label:'desequilíbrio'};render();};box.appendChild(b);});}}
function capture(side,idValue){active={side:side==='OPPONENT'?'B':(side||(['A','B'].find(s=>teamPlayers().some(p=>String(id(p))===String(idValue)))||'A')),shooterId:String(idValue),assist:null,imbalance:null};window.__pendingShotAttribution=null;setTimeout(render,0);}
function wrap(n){const o=window[n];if(typeof o!=='function'||o.__attr)return;const w=function(side,idValue,...r){capture(side,idValue);return o.call(this,side,idValue,...r)};w.__attr=true;window[n]=w;}
setInterval(()=>{wrap('openModal');wrap('openBilateralShot');render();},200);
